env:
  DOPPLER_PORT: 443
kubernetes:
  apiEndpoint: MASTER_URL 
prometheus:
  kubeStateMetrics:
    enabled: true
nginx:
  username: xxxxxxx
  password: xxxxxxxxxxxxxxxxx
services:
  loadbalanced: true

