module "gke-cluster" {
  source = "./cluster"

  location = var.location
  cluster_labels = var.cluster_labels
  instance_count = var.instance_count
  instance_type = var.instance_type
  disk_size_gb = var.disk_size_gb
  dns_credentials_json = var.dns_credentials_json
}

// kubeconfig will be generated by the GKE module

provider "helm" {
  version = "1.3.2"
  alias   = "helm-cap"

  kubernetes {
    config_path = "${path.cwd}/kubeconfig"
  }
}

module "helper-charts" {
  source = "./common/helper-charts"

  providers = {
    helm = helm.helm-cap
  }

  platform             = "gke"  //for common helper-charts' tmpl files

  service_provider     = "google"

  project              = var.project
  dns_credentials_json_secret_key_name = module.gke-cluster.dns_credentials_json_secret_key_name

  email                   = var.email

  depends_on = [
    module.gke-cluster
  ]
}

module "cap-charts" {
  source = "./common/cap-charts"

  providers = {
    helm = helm.helm-cap
  }

  cap_domain = var.cap_domain
  cluster_url = module.gke-cluster.cluster_url

  # One variable is initially applied to all security contexts,
  # override to create distinct passwords for each context
  cf_admin_password       = var.admin_password
  uaa_admin_client_secret = var.admin_password
  stratos_admin_password  = var.admin_password
  metrics_admin_password  = var.admin_password

  depends_on = [
    module.gke-cluster,
    module.helper-charts
  ]
}
