env:
  DOPPLER_PORT: 443

  prometheus:
  kubeStateMetrics:
    enabled: true

metrics:
    
  service:

    ingress:
      enabled: true

      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: metrics.tfe2e.susecap.biz

  username: admin
  password: password


cloudFoundry:
  apiEndpoint: https://api.tfe2e.susecap.biz
  uaaAdminClient: admin
  uaaAdminClientSecret: alsochangeme





